myChatApp:
  component: '@yugasun/serverless-chatapp'
  inputs:
    name: my-chat-app
    description: My Chat App
    region: ${env.REGION}

    # backend config to be passed to the socket component
    backend:
      region: ${env.REGION}
      functionName: chatapp
      code: ./backend
      functionConf:
        memorySize: 128
        timeout: 30
        vpcConfig:
          vpcId: ${env.VPC_ID}
          subnetId: ${env.SUBNET_ID}
        environment:
          variables:
            mongoConnectString: ${env.MONGO_CONNECTION}
      apigatewayConf:
        serviceTimeout: 30
        protocols:
          - https

    # frontend config to be passed to the website component
    frontend:
      protocol: https
      code:
        src: build
        root: frontend
        hook: npm run build
        envPath: ./src
