myChatApp:
  # component: '@yugasun/serverless-chatapp'
  component: ../
  inputs:
    name: my-chat-app
    description: My Chat App
    region: ap-guangzhou

    # backend config to be passed to the socket component
    backend:
      region: ap-guangzhou
      functionName: chatapp
      code: ./backend
      functionConf:
        memorySize: 128
        timeout: 10
        vpcConfig:
          vpcId: vpc-e0ty4dcx
          subnetId: subnet-ngamaqre
        environment:
          variables:
            mongoConnectString: ${env.MONGO_CONNECTION}
      apigatewayConf:
        serviceTimeout: 30
        protocols:
          - https

    # frontend config to be passed to the website component
    frontend:
      protocol: https
      code:
        src: build
        root: frontend
        hook: npm run build
        envPath: ./src
